vich_uploader:
    db_driver: orm


    metadata:
        type: attribute

    mappings:
        avatars:
            uri_prefix: '%avatar_folder%'
            upload_destination: '%kernel.project_dir%/public%avatar_folder%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
