# 1. Copier ce fichier dans le dossier de prod (en le renommant en compose.yaml)
# 2. Lancer les conteneurs avec : sudo docker compose up -d
services:
  php:
    image: emiliengibeaud/ecoride_api:latest
    container_name: ecoride_api
    restart: unless-stopped
    environment:
      APP_ENV: prod
      SERVER_NAME: api.ecoridedupicton.me
      # Doctrine ORM → MariaDB
      DATABASE_URL: "mysql://${MARIADB_USER}:${MARIADB_PASSWORD}@database:3306/${MARIADB_DATABASE}?serverVersion=${MARIADB_VERSION:-11.5.2}-MariaDB&charset=utf8mb4"
      # Doctrine ODM → MongoDB
      MONGODB_URL: "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongo:27017/"

    volumes:
      - avatars_data:/app/public/uploads

    networks:
      - edge_edge
      - ecoride_back

  database:
    image: mariadb:${MARIADB_VERSION}
    container_name: ecoride_db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - ecoride_back

  mongo:
    image: mongo:${MONGODB_VERSION}
    container_name: ecoride_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecoride_back

networks:
  edge_edge:
    external: true
  ecoride_back:
    external: true

volumes:
  avatars_data:
  mariadb_data:
  mongodb_data:
